name: Metasoft Solutions
favicon: null
layout_spectrum: 0.32396517717279494
typography_spectrum: 0.936826332937926
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.4807494920678437
  lightness: 0.8855052120052278
  saturation: 0.8398575619794428
  rhythmicContrast: 0.7117452083621174
purpose: []
